<?php
function e($valor): string
{
    return htmlspecialchars((string)$valor, ENT_QUOTES, 'UTF-8');
}
$kpis = $datos['kpis'];
$grupos = $datos['grupos'];
$alumnos = $datos['alumnos'];
$incidencias = $datos['incidencias'];
?>
<!doctype html>
<html lang="es">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Kairos | Dashboard</title>
<link rel="stylesheet" href="CSS/main.css">
<style>
body{display:block;padding:0;background:var(--fondo)}.dashboard{max-width:1280px;margin:auto;padding:32px}.encabezado{display:flex;justify-content:space-between;align-items:center;margin-bottom:28px}.encabezado h1{margin:0}.subtitulo{color:var(--texto-secundario)}.grid-kpi{display:grid;grid-template-columns:repeat(4,1fr);gap:16px;margin-bottom:24px}.kpi,.panel{background:var(--superficie);border:1px solid var(--borde);border-radius:16px;padding:20px;box-shadow:0 8px 24px rgba(0,0,0,.07)}.kpi small{color:var(--texto-secundario)}.kpi strong{display:block;font-size:32px;color:var(--morado-oscuro);margin-top:8px}.layout{display:grid;grid-template-columns:1fr 1fr;gap:20px;margin-bottom:20px}.panel h2{font-size:19px;margin:0 0 16px;color:var(--morado-oscuro)}.form-grid{display:grid;grid-template-columns:repeat(2,1fr);gap:12px}.campo{margin:0}.campo label{margin:0 0 6px;font-size:14px}.campo input,.campo select,.campo textarea{width:100%;padding:10px;border:1px solid var(--borde);border-radius:8px;font:inherit}.campo textarea{min-height:74px;resize:vertical}.campo.ancho{grid-column:1/-1}.acciones{display:flex;gap:8px;align-items:center}.acciones button,.acciones a{width:auto;margin:0;padding:9px 13px;text-decoration:none}.btn-secundario{background:var(--morado-claro);color:var(--morado-oscuro)}.btn-peligro{background:var(--error-texto)}.tabla-wrap{overflow:auto}table{width:100%;border-collapse:collapse;min-width:650px}th,td{text-align:left;padding:12px 10px;border-bottom:1px solid var(--borde);font-size:14px}th{color:var(--texto-secundario);font-size:12px;text-transform:uppercase}.estado{display:inline-flex;align-items:center;gap:6px;font-weight:bold}.estado:before{content:'';width:11px;height:11px;border-radius:50%;background:var(--exito-texto)}.estado-Amarillo:before{background:var(--amarillo)}.estado-Rojo:before{background:var(--error-texto)}.mensaje{display:none;margin:0 0 16px;padding:12px;border-radius:8px;background:var(--exito-fondo);color:var(--exito-texto)}.error{background:var(--error-fondo);color:var(--error-texto)}.vacio{color:var(--texto-secundario);text-align:center}@media(max-width:850px){.grid-kpi{grid-template-columns:repeat(2,1fr)}.layout{grid-template-columns:1fr}}@media(max-width:520px){.dashboard{padding:18px}.grid-kpi{grid-template-columns:1fr}.form-grid{grid-template-columns:1fr}.encabezado{display:block}}
</style>
</head>
<body>
<main class="dashboard">
<header class="encabezado"><div><h1>Panel de seguimiento</h1><div class="subtitulo">Gestión pedagógica y autorregulación emocional</div></div><div class="acciones"><a class="btn-secundario" href="accesos/maestro/registro_maestro.php">Registrar maestro</a><div class="subtitulo"><?= e($_SESSION['administrador_nombre'] ?? $_SESSION['maestro_nombre'] ?? 'Usuario') ?></div></div></header>
<div id="mensaje" class="mensaje"></div>
<section class="grid-kpi" aria-label="Indicadores principales"><div class="kpi"><small>Total de alumnos</small><strong id="kpi-alumnos"><?= e($kpis['alumnos']) ?></strong></div><div class="kpi"><small>Incidencias recientes</small><strong id="kpi-incidencias"><?= e($kpis['incidencias']) ?></strong></div><div class="kpi"><small>Contenciones</small><strong id="kpi-contenciones"><?= e($kpis['contenciones']) ?></strong></div><div class="kpi"><small>Pendientes</small><strong id="kpi-pendientes"><?= e($kpis['pendientes']) ?></strong></div></section>
<section class="layout"><article class="panel"><h2 id="titulo-grupo">Registrar grupo</h2><form id="form-grupo" class="form-grid"><input type="hidden" name="id_grupo"><div class="campo"><label>Grado</label><select name="grado" required><option value="">Selecciona</option><?php for($i=1;$i<=6;$i++): ?><option value="<?= $i ?>"><?= $i ?>°</option><?php endfor; ?></select></div><div class="campo"><label>Grupo</label><input name="grupo" maxlength="1" required></div><div class="campo ancho"><label>Ciclo escolar</label><input name="ciclo_escolar" placeholder="2025-2026" required></div><div class="acciones ancho"><button>Guardar grupo</button><button type="button" class="btn-secundario" onclick="limpiarGrupo()">Limpiar</button></div></form><div class="tabla-wrap"><table><thead><tr><th>Grupo</th><th>Ciclo</th><th>Acciones</th></tr></thead><tbody id="tabla-grupos"><?php foreach($grupos as $grupo): ?><tr><td><?= e($grupo['grado'].'°'.$grupo['grupo']) ?></td><td><?= e($grupo['ciclo_escolar']) ?></td><td class="acciones"><button type="button" data-editar-grupo='<?= e(json_encode($grupo, JSON_UNESCAPED_UNICODE)) ?>'>Editar</button><button type="button" class="btn-peligro" onclick="eliminar('eliminar_grupo','id_grupo',<?= (int)$grupo['id_grupo'] ?>)">Baja</button></td></tr><?php endforeach; ?></tbody></table></div></article>
<article class="panel"><h2 id="titulo-alumno">Registrar alumno</h2><form id="form-alumno" class="form-grid"><input type="hidden" name="id_alumno"><div class="campo"><label>Nombre</label><input name="nombre" required></div><div class="campo"><label>Apellido paterno</label><input name="apellido_paterno" required></div><div class="campo"><label>Apellido materno</label><input name="apellido_materno"></div><div class="campo"><label>Edad</label><input name="edad" type="number" min="5" max="18"></div><div class="campo ancho"><label>Grupo</label><select name="id_grupo" required><option value="">Selecciona un grupo</option><?php foreach($grupos as $grupo): ?><option value="<?= (int)$grupo['id_grupo'] ?>"><?= e($grupo['grado'].'°'.$grupo['grupo'].' · '.$grupo['ciclo_escolar']) ?></option><?php endforeach; ?></select></div><div class="acciones ancho"><button>Guardar alumno</button><button type="button" class="btn-secundario" onclick="limpiarAlumno()">Limpiar</button></div></form></article></section>
<section class="panel"><h2>Semáforo emocional</h2><div class="tabla-wrap"><table><thead><tr><th>Alumno</th><th>Grupo</th><th>Edad</th><th>Estado emocional</th><th>Acciones</th></tr></thead><tbody id="tabla-alumnos"><?php foreach($alumnos as $alumno): ?><tr><td><?= e($alumno['nombre'].' '.$alumno['apellido_paterno'].' '.$alumno['apellido_materno']) ?></td><td><?= e($alumno['grado'].'°'.$alumno['grupo']) ?></td><td><?= e($alumno['edad'] ?? '—') ?></td><td><span class="estado estado-<?= e($alumno['estado_semaforo']) ?>"><?= e($alumno['estado_semaforo']) ?></span></td><td class="acciones"><button type="button" data-editar-alumno='<?= e(json_encode($alumno, JSON_UNESCAPED_UNICODE)) ?>'>Editar</button><button type="button" class="btn-peligro" onclick="eliminar('eliminar_alumno','id_alumno',<?= (int)$alumno['id_alumno'] ?>)">Baja</button></td></tr><?php endforeach; ?></tbody></table></div></section>
<section class="layout"><article class="panel"><h2>Incidencia rápida</h2><form id="form-incidencia" class="form-grid"><div class="campo ancho"><label>Alumno</label><select name="id_alumno" required><option value="">Selecciona un alumno</option><?php foreach($alumnos as $alumno): ?><option value="<?= (int)$alumno['id_alumno'] ?>"><?= e($alumno['nombre'].' '.$alumno['apellido_paterno']) ?></option><?php endforeach; ?></select></div><div class="campo"><label>Tipo de contención</label><select name="accion_contencion" required><option value="">Selecciona</option><option>Respiración guiada</option><option>Pausa activa</option><option>Acompañamiento</option><option>Diálogo emocional</option></select></div><div class="campo"><label>Emoción detectada</label><select name="emocion" required><option value="">Selecciona</option><option>Tranquilidad</option><option>Ansiedad</option><option>Frustración</option><option>Tristeza</option><option>Enojo</option></select></div><div class="campo ancho"><label>Descripción</label><textarea name="nota_descripcion" required></textarea></div><div class="acciones ancho"><button>Guardar incidencia</button></div></form></article><article class="panel"><h2>Últimas incidencias</h2><div class="tabla-wrap"><table><thead><tr><th>Fecha</th><th>Alumno</th><th>Emoción</th><th>Contención</th></tr></thead><tbody id="tabla-incidencias"><?php foreach($incidencias as $incidencia): ?><tr><td><?= e($incidencia['fecha_hora']) ?></td><td><?= e($incidencia['alumno']) ?></td><td><?= e($incidencia['emocion']) ?></td><td><?= e($incidencia['accion_contencion']) ?></td></tr><?php endforeach; ?></tbody></table></div></article></section>
</main>
<script>
const endpoint='dashboard.php';
const mensaje=document.getElementById('mensaje');
function avisar(texto,error=false){mensaje.textContent=texto;mensaje.className=error?'mensaje error':'mensaje';mensaje.style.display='block';setTimeout(()=>mensaje.style.display='none',3500)}
async function enviar(form){const datos=new FormData(form);const respuesta=await fetch(endpoint,{method:'POST',body:datos});const json=await respuesta.json();if(!json.ok)throw new Error(json.error);avisar(json.mensaje);await refrescar()}
async function refrescar(){const respuesta=await fetch(endpoint+'?accion=datos');const json=await respuesta.json();if(!json.ok)return;const d=json.datos;document.getElementById('kpi-alumnos').textContent=d.kpis.alumnos;document.getElementById('kpi-incidencias').textContent=d.kpis.incidencias;document.getElementById('kpi-contenciones').textContent=d.kpis.contenciones;document.getElementById('kpi-pendientes').textContent=d.kpis.pendientes;document.getElementById('tabla-grupos').innerHTML=d.grupos.map(g=>`<tr><td>${g.grado}°${g.grupo}</td><td>${g.ciclo_escolar}</td><td class="acciones"><button type="button" data-editar-grupo='${encodeURIComponent(JSON.stringify(g))}' onclick="editarGrupo(this)">Editar</button><button type="button" class="btn-peligro" onclick="eliminar('eliminar_grupo','id_grupo',${g.id_grupo})">Baja</button></td></tr>`).join('');document.getElementById('tabla-alumnos').innerHTML=d.alumnos.map(a=>`<tr><td>${a.nombre} ${a.apellido_paterno} ${a.apellido_materno||''}</td><td>${a.grado}°${a.grupo}</td><td>${a.edad||'—'}</td><td><span class="estado estado-${a.estado_semaforo}">${a.estado_semaforo}</span></td><td class="acciones"><button type="button" data-editar-alumno='${encodeURIComponent(JSON.stringify(a))}' onclick="editarAlumno(this)">Editar</button><button type="button" class="btn-peligro" onclick="eliminar('eliminar_alumno','id_alumno',${a.id_alumno})">Baja</button></td></tr>`).join('');document.getElementById('tabla-incidencias').innerHTML=d.incidencias.map(i=>`<tr><td>${i.fecha_hora}</td><td>${i.alumno}</td><td>${i.emocion}</td><td>${i.accion_contencion}</td></tr>`).join('')}
async function eliminar(accion,campo,id){if(!confirm('¿Deseas dar de baja este registro?'))return;const form=new FormData();form.append('accion',accion);form.append(campo,id);try{const r=await fetch(endpoint,{method:'POST',body:form});const j=await r.json();if(!j.ok)throw new Error(j.error);avisar(j.mensaje);await refrescar()}catch(e){avisar(e.message,true)}}
function limpiarGrupo(){document.getElementById('form-grupo').reset();document.querySelector('#form-grupo [name=id_grupo]').value='';document.getElementById('titulo-grupo').textContent='Registrar grupo'}
function limpiarAlumno(){document.getElementById('form-alumno').reset();document.querySelector('#form-alumno [name=id_alumno]').value='';document.getElementById('titulo-alumno').textContent='Registrar alumno'}
document.getElementById('form-grupo').addEventListener('submit',async e=>{e.preventDefault();try{const f=new FormData(e.target);f.append('accion','guardar_grupo');const r=await fetch(endpoint,{method:'POST',body:f});const j=await r.json();if(!j.ok)throw new Error(j.error);avisar(j.mensaje);limpiarGrupo();await refrescar()}catch(x){avisar(x.message,true)}});
document.getElementById('form-alumno').addEventListener('submit',async e=>{e.preventDefault();try{const f=new FormData(e.target);f.append('accion','guardar_alumno');const r=await fetch(endpoint,{method:'POST',body:f});const j=await r.json();if(!j.ok)throw new Error(j.error);avisar(j.mensaje);limpiarAlumno();await refrescar()}catch(x){avisar(x.message,true)}});
document.getElementById('form-incidencia').addEventListener('submit',async e=>{e.preventDefault();try{const f=new FormData(e.target);f.append('accion','guardar_incidencia');const r=await fetch(endpoint,{method:'POST',body:f});const j=await r.json();if(!j.ok)throw new Error(j.error);avisar(j.mensaje);e.target.reset();await refrescar()}catch(x){avisar(x.message,true)}});
function editarGrupo(b){const d=JSON.parse(decodeURIComponent(b.dataset.editarGrupo));const f=document.getElementById('form-grupo');Object.keys(d).forEach(k=>{if(f.elements[k])f.elements[k].value=d[k]});document.getElementById('titulo-grupo').textContent='Editar grupo';f.scrollIntoView({behavior:'smooth'})}
function editarAlumno(b){const d=JSON.parse(decodeURIComponent(b.dataset.editarAlumno));const f=document.getElementById('form-alumno');Object.keys(d).forEach(k=>{if(f.elements[k])f.elements[k].value=d[k]});document.getElementById('titulo-alumno').textContent='Editar alumno';f.scrollIntoView({behavior:'smooth'})}
</script>
</body>
</html>
